# This is the name of your workflow. It will show up in the "Actions" tab on GitHub.
name: Capper-Ranks CI

# This section defines WHEN the workflow will run.
on:
  # Run on every push to the "main" branch.
  push:
    branches: [ "main" ]
  # Also run on every pull request that targets the "main" branch.
  pull_request:
    branches: [ "main" ]

# This section defines the sequence of jobs to run.
jobs:
  # The first job is called "lint".
  lint:
    # It runs on the latest version of Ubuntu Linux.
    runs-on: ubuntu-latest
    # These are the steps the job will take.
    steps:
    # Step 1: Checks out your repository's code so the job can access it.
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Sets up a specific version of Python.
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # You can change this to your desired Python version

    # Step 3: Installs the necessary Python packages for linting.
    - name: Install lint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    # Step 4: Runs the linter on your code.
    - name: Lint with flake8
      run: |
        # This checks for basic syntax errors and undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # This provides style warnings but doesn't fail the build.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # The second job is called "test".
  # In .github/workflows/main.yml

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e . 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with pytest
      run: |
        pytest